name: Lint, type-check, test

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test/requirements.txt
      - name: Linting
        run: |
          flake8 -v
          pylint metadata_extract src diff test *.py
      - name: Type-check
        run: mypy metadata_extract src diff main.py
      - name: Running tests
        run: python -m pytest -c test/pytest.ini --cov=metadata_extract
