name: CI/CD pipeline

on: [push]

env:
  APP_VERSION: ${{ github.ref_name }}

jobs:

  lint-and-test:
    name: Run linting, typecheck, and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test/requirements.txt

      - name: Linting
        run: |
          flake8 -v
          pylint metadata_extract src diff test *.py

      - name: Type-check
        run: mypy metadata_extract src diff main.py

      - name: Running tests
        run: python -m pytest --cov=metadata_extract

  build-and-publish:
    name: Create and push Docker image
    outputs:
      image_version: ${{ steps.meta.outputs.version }}
    needs: lint-and-test
    # if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: nationallibraryofnorway/meteor
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile
          build-args: |
            USE_GIELLA=true

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: nationallibraryofnorway/meteor
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md

  deploy-to-stage:
    name: Deploy to kubernetes stage environment
    needs: build-and-publish
    if: github.ref == 'refs/heads/main'
    uses: NationalLibraryOfNorway/tekst-workflows/.github/workflows/kubernetes-deploy.yml@main
    with:
      CLUSTER_NAME: "hstk8s"
      ENVIRONMENT: stage
      IMAGE_VERSION: ${{ needs.build-and-publish.outputs.image_version }}
    secrets:
      VAULT_URL: ${{ secrets.NB_VAULT_URL }}
      VAULT_SECRET_PATH: ${{ secrets.TEKST_VAULT_SECRET_PATH }}
      VAULT_ROLE_ID: ${{ secrets.TEKST_VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.TEKST_VAULT_SECRET_ID }}

  deploy-to-prod:
    name: Deploy to kubernetes prod environment
    needs: build-and-publish
    if: startsWith(github.event.ref, 'refs/tags/v')
    uses: NationalLibraryOfNorway/tekst-workflows/.github/workflows/kubernetes-deploy.yml@main
    with:
      CLUSTER_NAME: "hstk8s"
      ENVIRONMENT: prod
      IMAGE_VERSION: ${{ needs.build-and-publish.outputs.image_version }}
    secrets:
      VAULT_URL: ${{ secrets.NB_VAULT_URL }}
      VAULT_SECRET_PATH: ${{ secrets.TEKST_VAULT_SECRET_PATH }}
      VAULT_ROLE_ID: ${{ secrets.TEKST_VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.TEKST_VAULT_SECRET_ID }}
